trigger:
  branches:
    include:
      - master
  paths:  
    include: 
      - code/azureresources/*

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- bash: |
    mkdir -p "$(Build.ArtifactStagingDirectory)/azure"
    cp code/azureresources//azuredeploy.parameters.json "$(Build.ArtifactStagingDirectory)/azure/azuredeploy.parameters.json"
    cp code/azureresources//azuredeploy.json "$(Build.ArtifactStagingDirectory)/azure/azuredeploy.json"
  displayName: 'Prepare Azure Resource Manager template Build Artifacts'

- task: PublishBuildArtifacts@1
  displayName: Publish ARM Template Build Artifacts
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/azure'
    artifactName: azureresources