trigger:
  branches:
    include:
      - master

  paths:  
    include: 
      - code/database/ControlDb/*

pool:
  name: Azure Pipelines
  demands: msbuild
  vmImage: 'vs2017-win2016'

steps:
- task: MSBuild@1
  displayName: 'Build ControlDb'
  inputs:
    solution: code/database/ControlDb//ControlDb.sqlproj

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: code/database/ControlDb/bin/Debug
    artifactName: ControlDb
