CREATE TABLE [UTIL].[Calendar] (
    [DateKey]            INT          NOT NULL,
    [Date]               DATE         NOT NULL,
    [Day]                TINYINT      NOT NULL,
    [DaySuffix]          CHAR (2)     NOT NULL,
    [Weekday]            TINYINT      NOT NULL,
    [WeekDayName]        VARCHAR (10) NOT NULL,
    [IsWeekend]          BIT          NOT NULL,
    [DayOfYear]          SMALLINT     NOT NULL,
    [WeekOfMonth]        TINYINT      NOT NULL,
    [WeekOfYear]         TINYINT      NOT NULL,
    [Month]              TINYINT      NOT NULL,
    [MonthID]            VARCHAR (10) NOT NULL,
    [MonthName]          VARCHAR (10) NOT NULL,
    [ShortMonthYearName] VARCHAR (10) NOT NULL,
    [Quarter]            TINYINT      NOT NULL,
    [QuarterName]        VARCHAR (6)  NOT NULL,
    [HalfYearName]       VARCHAR (6)  NOT NULL,
    [Year]               INT          NOT NULL,
    [FirstDayOfWeek]     DATE         NOT NULL,
    [FirstDayOfMonth]    DATE         NOT NULL,
    [LastDayOfMonth]     DATE         NOT NULL,
    [FirstDayOfQuarter]  DATE         NOT NULL,
    [LastDayOfQuarter]   DATE         NOT NULL,
    [FirstDayOfYear]     DATE         NOT NULL,
    [LastDayOfYear]      DATE         NOT NULL,
    [FiscalYear]         INT          NOT NULL,
    [FiscalName]         VARCHAR (6)  NOT NULL,
    [FiscalQuarterName]  VARCHAR (6)  NOT NULL,
    [FiscalHalfYearName] VARCHAR (6)  NOT NULL,
    [FiscalStartDate]    DATE         NOT NULL,
    [FiscalEndDate]      DATE         NOT NULL,
    [FiscalMonth]        TINYINT      NOT NULL,
    [FiscalMonthName]    VARCHAR (10) NOT NULL,
    PRIMARY KEY CLUSTERED ([DateKey] ASC)
);

